package:
  name: conda-depgraph
  version: 1.2.0

about:
  home: https://github.com/omegacen/conda-depgraph
  license: LGPL
  license_file: LICENSE
  summary: A command-line utility to plot Conda dependency graphs.

source:
  - path: ../src
    folder: src
  - path: ../tests
    folder: tests
  - path: ../LICENSE

requirements:
  run:
    - python>=3.6
    - asciinet
    - click
    - conda
    - networkx

build:
  noarch: python
  script:
    - mkdir -p ${SP_DIR}
    - cp -r src/* ${SP_DIR}
  entry_points:
    - conda-depgraph = conda_depgraph.cli:main

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-console-scripts
  source_files:
    - tests/*.py
  imports:
    - conda_depgraph
    - asciinet
  commands:
    - pytest
        --cov=${SP_DIR}/conda_depgraph
        --cov-report term-missing
        --script-launch-mode=subprocess
        tests/
